config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
   
    before_action :authenticate_user!, only: [:new, :create]  
  
    def index
      @students = Student.all
   end 
  
   def new
      @student = Student.new
   end
  
   def create
      student = Student.new(student_params)
      student.user_id = current_user.id
      if student.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
   end
  
   def show
      @student = Student.find(params[:id])
   end
  
   def edit
      @student = Student.find(params[:id])
   end
  
   def update
      student = Student.find(params[:id])
      if student.update(student_params)
        redirect_to :action => "show", :id => student.id
      else
        redirect_to :action => "new"
      end
   end
  
   def destroy
      student = Student.find(params[:id])
      student.destroy
      redirect_to action: :index
   end
  
   private
   def student_params
      params.require(:student).permit(:name, :mentor, :grade)
   end
  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekkobe2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.label :mentor %>
    <%= f.text_field :mentor, :size => 140 %> 
    <%= f.label :grade %>
    <%= f.text_field :grade, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/students/index.html.erb
<h1>geekkobe2</h1>
<h3>Student一覧</h3>
<%= link_to "新規投稿へ", new_student_path %>
<div class="students-container">
  <% @students.each do |t| %>
    <div class="student">
      <%= t.user.email %>
      <%= t.name %>
      <%= t.mentor %>
      <%= t.grade %>
      <%= t.created_at %>
      <%= link_to"詳細へ", student_path(t.id) %>
      <%= link_to "編集する", edit_student_path(t.id) %>
      <%= button_to "削除する", student_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

  <% if user_signed_in? %>
    <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "新規登録", new_user_registration_path %></li>
    <li><%= link_to "ログイン", new_user_session_path %></li>
  <% end %>

app/views/students/new.html.erb
<h1>Geekkobe2</h1>
<h3>新規Student</h3>
<%= form_for @student do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %>
    <%= f.label :mentor %>
    <%= f.text_field :mentor, :size => 140 %>
    <%= f.label :grade %>
    <%= f.text_field :grade, :size => 140 %>
  </div>
  <%= f.submit "記録する" %>
<% end %>
<%= link_to "Student一覧に戻る", students_path %>

app/views/students/show.html.erb
<h1>geekkobe2</h1>
<h3>Student詳細</h3>
<div class="student">
  <p><%= @student.name %></p>
  <p><%= @student.mentor %></p>
  <p><%= @student.grade %></p>
  <p><%= @student.created_at %></p>
</div>

<%= link_to "Student一覧に戻る", students_path %>
<%= link_to "編集する", edit_student_path(@student.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>